### ISSUE TITLE
Usage of pxe protocol / networking

### ISSUE THREAD

**Issue by notzortex** [gurry/efi#50]
This probably isn't an issue with the project itself, but my understanding of how pxe / networking works.
Is there anything special that needs to be done to get it to work? using the example application on hardware just hangs without printing anything about pxe or DHCP, and on VMware it prints ">> Start pxe over ipv4" and then timeouts a bit after.
Any help in understanding would be appreciated :)

**Comment by gurry** [comment]
@notzortex Sorry for the delay in replying.

Are you using a wired network card? PXE works only on wired/Ethernet cards. It doesn't work over WiFi

**Comment by notzortex** [comment]
I'm not, I'm using ethernet built into motherboard (for the testing on hardware)

**Comment by gurry** [comment]
Okay thanks.

For PXE to work you also need a PXE server on the same LAN as the machine on which you're running the EFI application. This server will reply to PXE requests emitted by the EFI application and help it complete the PXE boot sequence. Do you have such a server set up?

Also, I have made some changes recently in the crate so it is possible that I've broken something. I haven't had any chance to test yet. Will test it and see if I can reproduce the issue.

**Comment by notzortex** [comment]
Ah I see, I thought so but the way it was used in the example app made me think it was possible to use it without it, but that is probably just my misunderstanding.

**Comment by gurry** [comment]
@notzortex Please do let me know if you still run into problems because there could be issues caused by the latest untested changes.

I will also update the README and mention the requirement of a PXE server.
